import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { mockVehicles } from "@/data/mock-vehicles";
import { mockAlertsData } from "@/data/mock-alerts";

type LocaleOption = "ar" | "en";

interface ReportOptions {
  locale: LocaleOption;
  companyName: string;
  dateRange: string;
}

// English localization mapping for PDF elements
const dict = {
  ar: {
    title: "Weekly Fleet Summary", // Simplified standard font mapping
    company: "Company: ",
    dateRange: "Date: ",
    summary: "Fleet Summary",
    stats: {
      totalVehicles: "Total Vehicles",
      avgHealth: "Average Health Score",
      totalAlerts: "Active Alerts",
      critical: "Critical Vehicles",
    },
    attention: "Top 5 Vehicles Needing Attention",
    metrics: {
      plate: "Plate",
      model: "Model",
      score: "Health Score",
      status: "Status"
    },
    alertsSummary: "Alerts Summary",
    alertsSeverity: {
      critical: "Critical",
      warning: "Warning",
      info: "Info"
    },
    count: "Count",
    footer: "Generated by FleetAI - Page "
  },
  en: {
    title: "Weekly Fleet Summary",
    company: "Company: ",
    dateRange: "Date Range: ",
    summary: "Fleet Summary",
    stats: {
      totalVehicles: "Total Vehicles",
      avgHealth: "Avg Health Score",
      totalAlerts: "Total Alerts",
      critical: "Vehicles < 40 Score",
    },
    attention: "Top 5 Vehicles Needing Attention",
    metrics: {
      plate: "Plate Number",
      model: "Model",
      score: "Health Score",
      status: "Status"
    },
    alertsSummary: "Alerts Summary by Severity",
    alertsSeverity: {
      critical: "Critical",
      warning: "Warning",
      info: "Info"
    },
    count: "Count",
    footer: "Generated by FleetAI - Page "
  }
};

export function generateWeeklyReport({ locale, companyName, dateRange }: ReportOptions) {
  // Use 'en' dictionary exclusively as requested due to Arabic font limitation in standard jsPDF
  const text = dict[locale === "ar" ? "ar" : "en"]; 
  
  // Initialize PDF
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.width;
  const marginX = 15;
  let currentY = 20;

  // Colors
  const primaryColor: [number, number, number] = [36, 113, 163]; // #2471A3
  
  // --- HEADER ---
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("FleetAI", marginX, currentY);
  
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text(text.title, pageWidth - marginX, currentY, { align: "right" });
  
  currentY += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  
  doc.text(`${text.company}${companyName}`, marginX, currentY);
  doc.text(`${text.dateRange}${dateRange}`, pageWidth - marginX, currentY, { align: "right" });
  
  currentY += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(marginX, currentY, pageWidth - marginX, currentY);
  currentY += 15;

  // --- COMPUTE STATS ---
  const totalVehicles = mockVehicles.length;
  const avgHealth = Math.round(mockVehicles.reduce((sum, v) => sum + v.health_score, 0) / totalVehicles);
  const criticalVehicles = mockVehicles.filter(v => v.health_score < 40).length;
  const totalAlerts = mockAlertsData.filter(a => a.status === "new").length;

  const getStatusText = (score: number) => {
    if (score >= 70) return "Good";
    if (score >= 40) return "Fair";
    return "Critical";
  };

  // --- SUMMARY SECTION ---
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(text.summary, marginX, currentY);
  currentY += 8;

  // Stat boxes using autoTable
  autoTable(doc, {
    startY: currentY,
    theme: 'grid',
    head: [[
      text.stats.totalVehicles, 
      text.stats.avgHealth, 
      text.stats.totalAlerts, 
      text.stats.critical
    ]],
    body: [[
      totalVehicles.toString(), 
      `${avgHealth}%`, 
      totalAlerts.toString(), 
      criticalVehicles.toString()
    ]],
    headStyles: { fillColor: primaryColor, textColor: 255, halign: 'center', fontStyle: 'bold' },
    bodyStyles: { halign: 'center', fontSize: 12, textColor: 50 },
    margin: { left: marginX, right: marginX }
  });

  currentY = (doc as any).lastAutoTable.finalY + 15;

  // --- VEHICLES NEEDING ATTENTION ---
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(text.attention, marginX, currentY);
  currentY += 8;

  const topCritical = [...mockVehicles]
    .sort((a, b) => a.health_score - b.health_score)
    .slice(0, 5)
    .map(v => [
      v.plate_number, 
      `${v.make} ${v.model}`, 
      v.health_score.toString(), 
      getStatusText(v.health_score)
    ]);

  autoTable(doc, {
    startY: currentY,
    head: [[text.metrics.plate, text.metrics.model, text.metrics.score, text.metrics.status]],
    body: topCritical,
    theme: 'striped',
    headStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
    columnStyles: {
      0: { fontStyle: 'bold' },
      2: { halign: 'center' }
    },
    didParseCell: function(data) {
      // Color-code the health score and status column
      if (data.section === 'body' && (data.column.index === 2 || data.column.index === 3)) {
        const rawRowData = data.row.raw as unknown as string[];
        const score = parseInt(rawRowData[2], 10);
        if (score < 40) {
          data.cell.styles.textColor = [220, 38, 38]; // Red
        } else if (score < 70) {
          data.cell.styles.textColor = [202, 138, 4]; // Yellow
        } else {
          data.cell.styles.textColor = [22, 163, 74]; // Green
        }
      }
    },
    margin: { left: marginX, right: marginX }
  });

  currentY = (doc as any).lastAutoTable.finalY + 15;

  // --- ALERTS SUMMARY ---
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(text.alertsSummary, marginX, currentY);
  currentY += 8;

  let criticalAlerts = 0, warningAlerts = 0, infoAlerts = 0;
  mockAlertsData.forEach(a => {
    if (a.status === "new") {
      if (a.severity === "critical") criticalAlerts++;
      else if (a.severity === "warning") warningAlerts++;
      else infoAlerts++;
    }
  });

  autoTable(doc, {
    startY: currentY,
    head: [["Severity", text.count]],
    body: [
      [text.alertsSeverity.critical, criticalAlerts.toString()],
      [text.alertsSeverity.warning, warningAlerts.toString()],
      [text.alertsSeverity.info, infoAlerts.toString()]
    ],
    theme: 'striped',
    headStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
    margin: { left: marginX, right: marginX },
    tableWidth: 100
  });

  // --- FOOTER ---
  const pageCount = (doc.internal as any).getNumberOfPages();
  const today = new Date().toLocaleDateString("en-US", { year: 'numeric', month: 'short', day: 'numeric' });
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(
      `${text.footer}${i} | ${today}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  // Generate File Output
  const filename = `FleetAI_Weekly_Report_${Date.now()}.pdf`;
  doc.save(filename);
}
